// Copyright (c) Bruno Sales <me@baliestri.dev>. Licensed under the MIT License.
// See the LICENSE file in the repository root for full license text.

using System.Management.Automation.Runspaces;
using PSLoom.Warp.Hooks;

namespace PSLoom.Runtime.Hooks;

/// <summary>
///   Entry points called from PowerShell script text generated by PSLoom (the wrapped <c>prompt</c>). Never throws: a failure
///   here would break prompt rendering.
/// </summary>
public static class HookBridge {
  /// <summary>
  ///   Raises <see cref="HookKind.SessionStarting" /> once, then <see cref="HookKind.PrePrompt" />, for the current runspace.
  ///   The prompt runs on the runspace's own thread, where <see cref="Runspace.DefaultRunspace" /> is reliable.
  /// </summary>
  public static void PrePrompt() {
    try {
      if (Runspace.DefaultRunspace is not { } runspace ||
          !HookBus.PerRunspace.TryGet(runspace, out var bus)) {
        return;
      }

      bus.RaiseSessionStarting();
      bus.Dispatch(HookKind.PrePrompt);
    }
    catch (Exception exception) when (exception is not (OutOfMemoryException or StackOverflowException)) {
      // Last-resort guard; the dispatcher already isolates handlers.
    }
  }
}
